# Generated by Django 5.0.6 on 2024-06-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Podcast Title')),
                ('poster', models.URLField(blank=True, null=True, verbose_name='Poster URL')),
                ('description', models.TextField(verbose_name='Podcast Description')),
                ('theme', models.CharField(max_length=255, verbose_name='Podcast Theme')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('topics', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Episode Title')),
                ('poster', models.URLField(blank=True, null=True, verbose_name='Poster URL')),
                ('description', models.TextField(verbose_name='Episode Description')),
                ('theme', models.CharField(max_length=255, verbose_name='Episode Theme')),
                ('guests', models.CharField(max_length=255, verbose_name='Guests')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcasts', verbose_name='Podcast')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['podcast', 'title'],
                'indexes': [models.Index(fields=['podcast', 'title'], name='podcasts_ep_podcast_597211_idx')],
            },
        ),
    ]
