# Generated by Django 5.0.6 on 2024-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Podcast Theme'),
        ),
    ]
