# Generated by Django 5.0.6 on 2024-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_episodes_options_alter_podcasts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='poster',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='theme',
            field=models.CharField(default='', max_length=255, verbose_name='Podcast Theme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='topics',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
