# Generated by Django 5.0.6 on 2024-06-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_alter_podcasts_poster_alter_podcasts_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='duration',
            field=models.DurationField(default=0, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='guests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Guests'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster URL'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Episode Theme'),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='poster',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Podcast Theme'),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='topics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
