# Generated by Django 5.0.6 on 2024-06-04 08:19

import podcasts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_episodes_duration_alter_episodes_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=podcasts.models.episode_poster),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=podcasts.models.podcast_poster),
        ),
    ]
