# Generated by Django 5.0.6 on 2024-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_episodes_poster_alter_podcasts_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='theme',
            field=models.JSONField(blank=True, null=True, verbose_name='Episode Theme'),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='theme',
            field=models.JSONField(blank=True, null=True, verbose_name='Podcast Theme'),
        ),
    ]
