# Generated by Django 5.0.6 on 2024-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_alter_episodes_theme_alter_podcasts_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='theme',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Episode Theme'),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='theme',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Podcast Theme'),
        ),
    ]
